# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "#xoxor4d's - Bug Research / ex. Bouncepatch.com / Tutorials and Tools"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Call of Duty - Bug Research / ex. Bouncepatch.com / Tutorials and Tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xoxor4d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: favico.png
author.name: xoxor4d
keywords: call of duty, cod, bug research, bouncepatch, bounce depatch, cod4 hlsl, custom hlsl shaders, iw3xo, visible clip

# Footer -------------------
footer-content: Content on this site has been created purely for the purposes of academic research. Project maintainers are not responsible or liable for misuse of any content provided.
# Social
githubUsername: xoxor4d
twitterUsername: xoxor4d
youtubeUsername: UC7DiUO6bzZGii0EUx1Vg4mw
steamUsername: xoxor4d


# Build settings
markdown: kramdown

themeColor: main
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _projects, _tutorials]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

collections:
  projects:
    output: true
  tutorials:
    output: true

# Build settings
#remote_theme: alexcarpenter/material-jekyll-theme
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
